name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  versionNumber : "1.0.${{ env.GITHUB_RUN_NUMBER}}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: compile n package docker image
      run: |
        mvn -B spring-boot:build-image \
          -Dimage.tag=${{ env.versionNumber }} \
          -Dimage.sha=$GITHUB_SHA
    
    - name: docker images
      run: docker images
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/samitkumarpatel/springboot-reactive'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Log in to the Container registry
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        docker push -a ghcr.io/samitkumarpatel/springboot-reactive
  helm:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && success() }}
    steps:
    - uses: actions/checkout@v3
    - name: helm validate/lint
      run: helm lint helm/
    - name: helm package
      run: |
        mkdir -p helm/charts
        helm package --destination helm/charts --version ${{ env.versionNumber }} --app-version ${{ env.versionNumber }} helm/
    - name: helm registry login
      run: |
        echo ${{secrets.GITHUB_TOKEN}} | helm registry login ghcr.io/${{ github.actor }} --username ${{ github.actor }} --password-stdin
    - name: helm push
      run: |
        helm push helm/charts/${{ github.event.repository.name }}-${{ env.versionNumber }}.tgz oci://ghcr.io/${{ github.repository }}